### ISSUE TITLE
Fix Website Font Consistency

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1024] opened 2021-08-02 00:11 UTC
- All the text used in the website should have the same font
- New Font: [Frank Ruhl Libre](https://fonts.google.com/specimen/Frank+Ruhl+Libre?query=Frank+Ruhl+Libre)
- Remove the import of any other fonts from html or css files that would not be required anymore

**Comment by ArihantJain123** [comment] 2021-08-02 10:57
please assign me this issue it will be helpful for me and I am LGMSOC participant

**Comment by ArihantJain123** [comment] 2021-08-03 06:49
Ok , Thanks for assign me this issue.

**Comment by AnirudhPanda** [comment] 2021-08-05 16:43
I can do this if nobody else is assigned!

**Comment by imjonsnow362** [comment] 2021-08-15 08:31
Is the issue fixed ?

**Comment by smaranjitghose** [comment] 2021-08-15 12:55
Not yet~

**Comment by AnirudhPanda** [comment] 2021-08-15 13:05
#1032

**Comment by shreyas1925** [comment] 2021-08-16 14:54
If at all the issue is not fixed please assign it to me.

**Comment by harshil202** [comment] 2021-08-30 07:15
You can assign me for this work I can do this.

**Comment by shreya-gb** [comment] 2021-08-31 05:57
@smaranjitghose You want all the font to be from Poppins to Frank Ruhl Libre?

**Comment by FidalMathew** [comment] 2021-09-22 08:02
I would like to work on the issue if available, please assign it to me.

**Comment by riyajha2305** [comment] 2021-10-15 23:53
Can I be assigned this issue?

**Closed** 2022-01-16 20:37 UTC
Labels: good first issue
