### ISSUE TITLE
[React] Research Page Button Fix

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1210] opened 2022-02-27 09:33 UTC
# Current UI

![research_page](https://user-images.githubusercontent.com/46641503/155876872-ca7e8d48-3825-47dd-92dc-4c42bdcd3e8a.png)

- The abstract and citation text should only appear when the corresponding buttons are selected
- [Reference](https://portfolio.smaranjitghose.com/research.html)

**Comment by Devmindtk** [comment] 2022-03-02 10:40
I would like to work on this issue please assign it to me @smaranjitghose

**Comment by anushbhatia** [comment] 2022-03-02 16:06
Assigned for 3 days. Extension may be provided if required

**Comment by Devmindtk** [comment] 2022-03-02 18:34
> Assigned for 3 days. Extension may be provided if required

I think the issue is already solved by someone please check once . abstract button and CTE is working completely fine

**Comment by Devmindtk** [comment] 2022-03-05 20:16
> Assigned for 3 days. Extension may be provided if required

created a PR please check is it fine?

https://user-images.githubusercontent.com/91221069/156898687-af32f1b1-1b28-4e86-abee-6c42f4ab277f.mp4

**Comment by anushbhatia** [comment] 2022-03-05 21:23
> > Assigned for 3 days. Extension may be provided if required
> 
> created a PR please check is it fine?
> 
>  John.Doe._.Research.-.Google.Chrome.2022-03-06.01-45-56.mp4

I think you can go ahead for a PR with this.

**Comment by Devmindtk** [comment] 2022-03-06 15:42
> > > Assigned for 3 days. Extension may be provided if required
> > 
> > 
> > created a PR please check is it fine?
> > John.Doe._.Research.-.Google.Chrome.2022-03-06.01-45-56.mp4
> 
> I think you can go ahead for a PR with this.

created a NEW PR please check

**Closed** 2022-03-11 19:05 UTC
Labels: Hard, JWOC
