### ISSUE TITLE
Improve Education Timeline

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1146] opened 2022-01-16 20:31 UTC
## Instructions:

![awsm](https://user-images.githubusercontent.com/46641503/149676896-99161f1d-12ba-4bee-9f7b-e12c3cd385f0.png)

- Try improve both the cards and the overall timeline structure with new design and animations
- An idea you can work on is: the center line is replaced the illustration for a road and on hover down/up gets highlighted
- For the cards, try to incorporate images of the institution along with the new UI
- [Sample Reference](https://codepen.io/Carrly/full/LQPLez). Keep in mind that for our case the timeline is vertical and not horizontal.

**Comment by Jyoti6828** [comment] 2022-01-26 08:11
I want to work on this issue. Kindly please assign it to me.

**Comment by Jyoti6828** [comment] 2022-01-31 18:33
I want to work on this issue under JWOC. Kindly Assign it to me.

**Comment by raxvab** [comment] 2022-01-31 20:10
I want to work on this issue under JWOC

**Comment by anushbhatia** [comment] 2022-02-01 14:18
@Jyoti6828 the issue is assigned to you already what is the progress on that.

**Comment by Jyoti6828** [comment] 2022-02-01 18:25
@anushbhatia This issue is assigned to me before the coding phase started. I asked in discord there I got to know that commenting and assigning is valid after 1 Feb. So now I commented on it again because the previous one was considered invalid. Can you please tell me what should I do now?

**Comment by anushbhatia** [comment] 2022-02-01 23:08
Follow the description provided there in the inbox and proceed building it.

**Comment by Jyoti6828** [comment] 2022-02-02 05:13
Okay, Thank You!

**Comment by anushbhatia** [comment] 2022-02-05 17:47
any update @Jyoti6828 ?

**Comment by Jyoti6828** [comment] 2022-02-05 18:24
I'm try to do the changes.
I stuck on that image part. When that card are in alternate manner the Clg images are not visible. I'm trying to solve that.

**Comment by Devmindtk** [comment] 2022-02-10 06:17
@smaranjitghose  i have changed the background color of card as same as experience card please check is it fine?
![Screenshot (485)](https://user-images.githubusercontent.com/91221069/153349206-67ee5604-ed6a-4810-a695-f463de7fe233.png)

**Comment by anushbhatia** [comment] 2022-02-10 09:15
> @smaranjitghose i have changed the background color of card as same as experience card please check is it fine? ![Screenshot (485)](https://user-images.githubusercontent.com/91221069/153349206-67ee5604-ed6a-4810-a695-f463de7fe233.png)

this looks awesome you can create an PR for the same

**Comment by Devmindtk** [comment] 2022-02-10 09:28
> > @smaranjitghose i have changed the background color of card as same as experience card please check is it fine? ![Screenshot (485)](https://user-images.githubusercontent.com/91221069/153349206-67ee5604-ed6a-4810-a695-f463de7fe233.png)
> 
> this looks awesome you can create an PR for the same

created please check @smaranjitghose

**Comment by Jyoti6828** [comment] 2022-02-11 06:56
I can't see these new changes in my system. Do I have to do fetch upstream and clone it again?

**Closed** 2022-02-27 11:23 UTC
Labels: Medium, 🤩 Up for Grab, JWOC
